### ISSUE TITLE
Does not work with GitLab CI

### ISSUE THREAD

**Issue by Jamesking56** [cytopia/docker-ansible-lint#14]
Trying to use this on GitLab CI:

.gitlab-ci.yml
```yml
ansible-lint:
  image: cytopia/ansible-lint
  stage: lint
  script:
    - ansible-lint -R -x idempotency,ANSIBLE0010 *.yml --nocolor
```

Output from GitLab CI:

```
WARNING: Couldn't open sh - No such file or directory
```

**Comment by cytopia** [comment]
@Jamesking56 how does GitLab invoke it? Are you able to see the full run command?

**Comment by DutchessNicole** [comment]
Gitlab checks out the code repository inside a directory in /builds/\<namespace\>/\<project name\> and tries to cd into it.

From there it'll try to run the `script` block with any elements passed to it

so given this config:
```
stages:
  - lint
ansible-linter:
  variables:
    CI_DEBUG_TRACE: "true"
  image: cytopia/ansible-lint
  stage: lint
  tags: ['generic']
  script:
    - ansible-lint inventories/playbook.yml
```
gitlab starts a docker container, checks out the code as mentioned above, tries to cd to the code directory and that is where it fails.
It never gets to the script block where the ansible-lint command is.

**Comment by cytopia** [comment]
I am adding the option to have it run without any arguments by default (https://github.com/cytopia/docker-ansible-lint/issues/17)

https://github.com/cytopia/docker-ansible-lint/pull/18

**Comment by DutchessNicole** [comment]
```yaml
stages:
  - lint

ansible-linter:
  image: cytopia/ansible-lint
  stage: lint
  tags: ['generic']
  script:
    - echo $PATH
    - pwd
    - which ansible-lint
    - ansible-lint inventories/bootstrap.yml
    - ansible-lint inventories/configure.yml
```
Given the preceding gitlab-ci file, we still get the missing `sh` lines:

```bash
WARNING: Couldn't open sh - No such file or directory
WARNING: Couldn't open sh - No such file or directory
```
I looked through the linked issues #17 and #18 but I don't quite see how they relate to this issue?
Could you elaborate on what the fix would be?

**Comment by xmariopereira** [comment]
I have the same issue, running in gitlab too.

**Comment by ndegory** [comment]
I made it work by specifying an entrypoint:

```
default:
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]

stages:
  - lint

ansible-linter:
  stage: lint
  script:
    - ansible-lint *.yaml
  only:
    - merge_requests
    - master
```
